### ISSUE TITLE
Hello,what is the format of your dataset?

### ISSUE THREAD

**Issue by bumingjueli1** [zeroone-universe/AECNN_for_Speech_Enhancement#1]
Hello, I am also reading this paper recently. Your code is very clear. I tried running your code. What is the format of your dataset? I tried to use the TIMIT database downloaded by myself, but the code shows that the length of the data set is empty, I would like to ask the directory of the TIMIT folder is: TIMIT\TRAIN\DR1\FDAW0\ SA1.wav?Thanks！

**Comment by zeroone-universe** [comment]
Hi, thank you for your interest.
For this code, TIMIT dataset has to be pre-organized. Directory DATA_DIR/TARGET_TRAIN and DATA_DIR/TARGET_TEST would contain only WAV files of each trainset and testset of TIMIT dataset. Directory DATA_DIR/NOISY_TRAIN and DATA_DIR/NOISY_TEST should contain noisy version of WAV files of trainset and testset of TIMIT. Each matching wav files in TARGET_TEST - NOISY_TEST or TARGET_TRAIN - NOISY_TRAIN should have the same filename to make (Noisy speech, Clean speech) pair in the custom dataset module. For capital letter paths, refer to config.py.

Example would be like this. The path of this directory is DATA_DIR/TARGET_TRAIN, and DATA_DIR/NOISY_TRAIN would have WAVs with same name but noisy.
![image](https://user-images.githubusercontent.com/88872326/176100302-253d8743-a391-4638-a4ba-2f32b280431b.png)

**Comment by alalei123456** [comment]
Thanks  a lot!
